{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kubescout.fullname" . }}
  labels:
    {{- include "kubescout.labels" . | nindent 4 }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.httpRoute.rules }}
    {{- range .Values.httpRoute.rules }}
    - {{- if .matches }}
      matches:
        {{- toYaml .matches | nindent 8 }}
      {{- end }}
      backendRefs:
        {{- if .backendRefs }}
        {{- toYaml .backendRefs | nindent 8 }}
        {{- else }}
        - name: {{ include "kubescout.fullname" $ }}
          port: {{ $.Values.service.port }}
        {{- end }}
    {{- end }}
    {{- else }}
    - backendRefs:
        - name: {{ include "kubescout.fullname" . }}
          port: {{ .Values.service.port }}
    {{- end }}
{{- end }}
